openapi: 3.0.1
info:
  title: Users.Mail
  version: '2.1'
servers:
  - url: https://graph.microsoft.com/2.1/
    description: Core
paths:
  '/users/{user-id}/messages':
    get:
      tags:
        - users.message
      summary: Get messages from users
      operationId: users_ListMessages
      parameters:
        - name: user-id
          in: path
          description: 'key: user-id of user'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: user
        - $ref: '#/components/parameters/ApiVersionParameter'
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                title: Collection of message
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: '#/components/schemas/microsoft.graph.message'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
components:
  schemas:
    microsoft.graph.mailFolder:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: mailFolder
          type: object
          properties:
            displayName:
              type: string
              nullable: true
            parentFolderId:
              type: string
              nullable: true
            childFolderCount:
              maximum: 2147483647
              minimum: -2147483648
              type: integer
              format: int32
              nullable: true
            unreadItemCount:
              maximum: 2147483647
              minimum: -2147483648
              type: integer
              format: int32
              nullable: true
            totalItemCount:
              maximum: 2147483647
              minimum: -2147483648
              type: integer
              format: int32
              nullable: true
            wellKnownName:
              type: string
              nullable: true
    microsoft.graph.message:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.outlookItem'
        - title: message
          type: object
          properties:
            receivedDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              format: date-time
              nullable: true
            sentDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              format: date-time
              nullable: true
            hasAttachments:
              type: boolean
              nullable: true
            subject:
              type: string
              nullable: true
            bodyPreview:
              type: string
              nullable: true
            webLink:
              type: string
              nullable: true
    microsoft.graph.entity:
      title: entity
      type: object
      properties:
        id:
          type: string
    microsoft.graph.outlookItem:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: outlookItem
          type: object
          properties:
            createdDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              format: date-time
              nullable: true
            lastModifiedDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              format: date-time
              nullable: true
            changeKey:
              type: string
              nullable: true
            categories:
              type: array
              items:
                type: string
                nullable: true
    odata.error:
      required:
        - error
      type: object
      properties:
        error:
          $ref: '#/components/schemas/odata.error.main'
    odata.error.main:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/odata.error.detail'
        innererror:
          type: object
          description: The structure of this object is service-specific
    odata.error.detail:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
  responses:
    error:
      description: error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/odata.error'
  parameters:
    ApiVersionParameter:
      name: api-version
      in: query
      required: true
      schema:
        type: string
      description: MS Graph API version.
  securitySchemes:
    azureaadv2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
          tokenUrl: https://login.microsoftonline.com/common/oauth2/v2.0/token
          scopes: { }
security:
  - azureaadv2: [ ]