openapi: 3.0.0
info:
  title: NetworkManagementClient
  description: The Microsoft Azure Network management API.
  version: '2017-10-01'
servers:
  - url: https://management.azure.com
security:
  - azure_auth:
      - user_impersonation
paths:
  "/subscriptions/{subscriptionId}/providers/Microsoft.Network/virtualNetworks":
    get:
      tags:
        - VirtualNetworks
      operationId: VirtualNetworks_ListAll
      description: Gets all virtual networks in a subscription.
      parameters:
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
      responses:
        "200":
          description: Request successful. The operation returns a list of VirtualNetwork
            resources.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VirtualNetworkListResult"
            text/json:
              schema:
                $ref: "#/components/schemas/VirtualNetworkListResult"
      x-ms-pageable:
        nextLinkName: nextLink
  "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/virtualNetworks/{virtualNetworkName}/usages":
    get:
      operationId: VirtualNetworks_ListUsage
      description: Lists usage stats.
      parameters:
        - name: resourceGroupName
          in: path
          required: true
          description: The name of the resource group.
          schema:
            type: string
        - name: virtualNetworkName
          in: path
          required: true
          description: The name of the virtual network.
          schema:
            type: string
        - $ref: "#/components/parameters/ApiVersionParameter"
        - $ref: "#/components/parameters/SubscriptionIdParameter"
      responses:
        "200":
          description: Usage stats for vnet.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VirtualNetworkListUsageResult"
            text/json:
              schema:
                $ref: "#/components/schemas/VirtualNetworkListUsageResult"
      x-ms-pageable:
        nextLinkName: nextLink
components:
  parameters:
    SubscriptionIdParameter:
      name: subscriptionId
      in: path
      required: true
      description: The subscription credentials which uniquely identify the Microsoft Azure
        subscription. The subscription ID forms part of the URI for every
        service call.
      schema:
        type: string
    ApiVersionParameter:
      name: api-version
      in: query
      required: true
      description: Client API version.
      schema:
        type: string
  securitySchemes:
    azure_auth:
      type: oauth2
      description: Azure Active Directory OAuth2 Flow
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    VirtualNetworkPropertiesFormat:
      properties:
        addressSpace:
          type: string
          description: The AddressSpace that contains an array of IP address ranges that
            can be used by subnets.
        resourceGuid:
          type: string
          description: The resourceGuid property of the Virtual Network resource.
        provisioningState:
          type: string
          description: "The provisioning state of the PublicIP resource. Possible values
            are: 'Updating', 'Deleting', and 'Failed'."
        enableDdosProtection:
          type: boolean
          description: Indicates if DDoS protection is enabled for all the protected
            resources in a Virtual Network.
        enableVmProtection:
          type: boolean
          description: Indicates if Vm protection is enabled for all the subnets in a
            Virtual Network.
      description: Properties of the virtual network.
    VirtualNetwork:
      properties:
        properties:
          $ref: "#/components/schemas/VirtualNetworkPropertiesFormat"
        etag:
          type: string
          description: Gets a unique read-only string that changes whenever the resource is
            updated.
      description: Virtual Network resource.
    VirtualNetworkListResult:
      properties:
        value:
          type: array
          items:
            $ref: "#/components/schemas/VirtualNetwork"
          description: Gets a list of VirtualNetwork resources in a resource group.
        nextLink:
          type: string
          description: The URL to get the next set of results.
      description: Response for the ListVirtualNetworks API service call.
    VirtualNetworkListUsageResult:
      properties:
        value:
          type: array
          readOnly: true
          items:
            $ref: "#/components/schemas/VirtualNetworkUsage"
          description: VirtualNetwork usage stats.
        nextLink:
          type: string
          description: The URL to get the next set of results.
      description: Response for the virtual networks GetUsage API service call.
    VirtualNetworkUsage:
      properties:
        currentValue:
          type: number
          format: double
          readOnly: true
          description: Indicates number of IPs used from the Subnet.
        id:
          type: string
          readOnly: true
          description: Subnet identifier.
        limit:
          type: number
          format: double
          readOnly: true
          description: Indicates the size of the subnet.
        name:
          type: string
          readOnly: true
          description: The name containing common and localized value for usage.
        unit:
          type: string
          readOnly: true
          description: Usage units. Returns 'Count'
      description: Usage details for subnet.